replicaCount: 1

image:
  repository: php
  tag: "8.1-apache"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

phpMessage: "Hola Mundo desde PHP en Kubernetes con Helm!"

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: hola-php.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
