apiVersion: v1
kind: Service
metadata:
  name: {{ include "hola-mundo-helm.fullname" . }}
  labels:
    app: {{ include "hola-mundo-helm.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "hola-mundo-helm.name" . }}
