replicaCount: 1

image:
  repository: php
  pullPolicy: IfNotPresent
  tag: "8.1-apache"

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: false
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: hola-php-v2.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: []

phpMessage: "Hola mundo desde PHP v2!"
