apiVersion: v1
kind: ConfigMap
metadata:
  name: varnish-config
data:
  default.vcl: |
    vcl 4.1;

    backend default {
        .host = "hola-php-hola-mundo-helm.hola-php-apps.svc.cluster.local";
        .port = "80";
    }

    sub vcl_recv {
        return (hash);
    }

    sub vcl_backend_response {
        set beresp.ttl = 5m;
    }
